### ISSUE TITLE
Create tweet retrieval service

### ISSUE THREAD

**Issue by IgorGee** [hunter695/icebreaker-api#4]
@IgorGee commented on [Sun Mar 19 2017](https://github.com/hunter695/icebreaker-client/issues/7)

Features to include:

* retrieve tweets with a given hashtag
* retrieve the tweets within a timeframe

---

@jurddle commented on [Sat Mar 25 2017](https://github.com/hunter695/icebreaker-client/issues/7#issuecomment-289246135)

Done

---

@IgorGee commented on [Sun Mar 26 2017](https://github.com/hunter695/icebreaker-client/issues/7#issuecomment-289318902)

Again, don't close unless you refer to a commit.

**Comment by TheOnlyWei** [comment]
The function is in src/twitter.js named getWildcardFromTwitter. The usage is documented in the file.
The full SHA of the initial push that included that function:
787f2757f2ff4660b05215ea492b8e3a8618efd5
